name: Feature Request
description: Suggest a new feature or enhancement for LLM-CostOps
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please fill out this form to help us understand your request.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm the following before submitting
      options:
        - label: I have searched existing issues and discussions
          required: true
        - label: I have checked the roadmap
          required: true
        - label: This feature fits the scope of the project
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: |
        Describe the problem or limitation you're experiencing.
        Example: "As a DevOps engineer, I need to track costs per deployment environment..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like to see this problem solved?
      placeholder: |
        Describe your proposed solution in detail.
        Example: "Add a new 'environment' tag to usage records that can be used for cost breakdown..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternative solutions or workarounds have you considered?
      placeholder: |
        Describe any alternative solutions or features you've considered.
        Example: "I considered using existing tags, but that doesn't provide structured filtering..."
    validations:
      required: false

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Provide specific use cases for this feature
      placeholder: |
        Describe how you would use this feature.

        Example:
        1. Track costs separately for dev, staging, and production
        2. Generate environment-specific cost reports
        3. Set different budget alerts per environment
    validations:
      required: true

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - New LLM Provider Support
        - New Pricing Model
        - Cost Analysis Enhancement
        - Forecasting Enhancement
        - API Enhancement
        - CLI Enhancement
        - Export/Reporting Feature
        - Authentication/Authorization
        - Observability Enhancement
        - Kubernetes/Deployment Feature
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical (Blocking my use of the project)
        - High (Very important for my use case)
        - Medium (Would be nice to have)
        - Low (Minor enhancement)
    validations:
      required: true

  - type: dropdown
    id: user-impact
    attributes:
      label: User Impact
      description: How many users would benefit from this feature?
      options:
        - All users
        - Most users
        - Some users
        - Niche use case
        - Just me
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Ideas
      description: Do you have ideas about how to implement this?
      placeholder: |
        Share any technical implementation ideas you have.
        This is optional but helpful!

        Example:
        - Add 'environment' field to UsageRecord struct
        - Update database schema with migration
        - Add environment filter to query API
        - Update cost aggregation to group by environment
    validations:
      required: false

  - type: textarea
    id: api-example
    attributes:
      label: API Example
      description: If this involves API changes, show what the API would look like
      placeholder: |
        ```rust
        // Example of how the API might look
        let costs = client
            .costs()
            .filter_by_environment("production")
            .get()
            .await?;
        ```
      render: rust
    validations:
      required: false

  - type: textarea
    id: config-example
    attributes:
      label: Configuration Example
      description: If this involves configuration changes, show what it would look like
      placeholder: |
        ```yaml
        # Example configuration
        cost_tracking:
          dimensions:
            - environment
            - region
            - team
        ```
      render: yaml
    validations:
      required: false

  - type: dropdown
    id: breaking-change
    attributes:
      label: Breaking Change
      description: Would this be a breaking change?
      options:
        - "No"
        - "Yes"
        - "Unsure"
    validations:
      required: true

  - type: textarea
    id: migration-path
    attributes:
      label: Migration Path
      description: If breaking, how should users migrate?
      placeholder: Describe how users would migrate from the old behavior to the new
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, mockups, or references
      placeholder: |
        Add any other context, screenshots, links to similar features in other projects, etc.
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you like to help implement this?
      options:
        - label: I would be willing to submit a PR to implement this feature
          required: false
        - label: I would be willing to help test this feature
          required: false
        - label: I would be willing to write documentation for this feature
          required: false
