# Simplified Cloud Build configuration for LLM-CostOps dev deployment
# Skips tests and lint for faster iteration

substitutions:
  _SERVICE_NAME: llm-costops
  _REGION: us-central1
  _PROJECT_ID: agentics-dev
  _ARTIFACT_REGISTRY: us-central1-docker.pkg.dev/agentics-dev/llm-devops
  _VERSION: dev

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8

steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build'
    args:
      - 'build'
      - '-t'
      - '${_ARTIFACT_REGISTRY}/${_SERVICE_NAME}:${_VERSION}'
      - '-t'
      - '${_ARTIFACT_REGISTRY}/${_SERVICE_NAME}:latest'
      - '-f'
      - 'deployment/gcp/Dockerfile.cloudrun'
      - '.'

  # Step 2: Push to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push'
    args:
      - 'push'
      - '--all-tags'
      - '${_ARTIFACT_REGISTRY}/${_SERVICE_NAME}'
    waitFor: ['build']

  # Step 3: Deploy to Cloud Run (dev)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-dev'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}-dev'
      - '--image'
      - '${_ARTIFACT_REGISTRY}/${_SERVICE_NAME}:${_VERSION}'
      - '--region'
      - '${_REGION}'
      - '--project'
      - '${_PROJECT_ID}'
      - '--platform'
      - 'managed'
      - '--no-allow-unauthenticated'
      - '--service-account'
      - 'llm-costops-sa@${_PROJECT_ID}.iam.gserviceaccount.com'
      - '--set-env-vars'
      - 'PLATFORM_ENV=dev,SERVICE_NAME=${_SERVICE_NAME},SERVICE_VERSION=${_VERSION}'
      - '--set-secrets'
      - 'RUVECTOR_API_KEY=ruvector-api-key:latest'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--timeout'
      - '60s'
      - '--concurrency'
      - '80'
    waitFor: ['push']

images:
  - '${_ARTIFACT_REGISTRY}/${_SERVICE_NAME}:${_VERSION}'
  - '${_ARTIFACT_REGISTRY}/${_SERVICE_NAME}:latest'

timeout: '1800s'
